config/routes.rb
Rails.application.routes.draw do

  #get 'relationships/follow_user'

  #get 'relationships/unfollow_user'
  post ':username/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':username/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user

  resources :comments
  # full /pins resources
  resources :pins, path: 'files' do
    member do
      post '/like' => 'pins#like'
    end
  end

  devise_for :users
  resources :users do
    resources :pins, only: [:index]
    member do
      get :following, :followers
    end
  end
  get 'users/:id/' => 'users#show', :as => :user_page

  mount ActionCable.server => '/cable'

  root 'pins#index'
  get "about" => "pages#about"
  get "contact" => "pages#contact"
  get "faq" => "pages#faq"
  get "how-it-works" => "pages#how_it_works"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :pin

  validates :content, presence: true

  after_create_commit { CommentBroadcastJob.perform_later(self) }
end

app/models/follow.rb
class Follow < ActiveRecord::Base
  belongs_to :follower, foreign_key: 'follower_id', class_name: 'User'
  belongs_to :following, foreign_key: 'following_id', class_name: 'User'
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :pin
  validates_uniqueness_of :pin_id, scope: :user_id
  validates_presence_of :pin_id
  validates_presence_of :user_id
end

app/models/pin.rb
class Pin < ActiveRecord::Base
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :comments, dependent: :destroy

  has_attached_file :image, styles: { medium: "700x500#", small: "350x250#" }
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]

  validates :image, presence: true
  validates :description, presence: true

  def count_views
    self.view ||= 0
    self.view += 1
    self.save
  end

  def self.pin_search(query)
    pins = self.joins(:user)
    pins = pins.where("description LIKE ? OR users.username LIKE ? ", "%#{query}%", "%#{query}%") if query.present?
    pins
  end

  def to_param
    description.downcase.split[0..4].join('-')
  end


  def self.find_by_param(input)
    input = input.split('-').join(' ')
    where("LOWER(description) LIKE ?",  "#{input}%").last
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :pins, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_pins, through: :likes, source: :pin
  has_many :comments, dependent: :destroy
  has_many :follower_relationships, foreign_key: :following_id, class_name: 'Follow'
  has_many :followers, through: :follower_relationships, source: :follower

  has_many :following_relationships, foreign_key: :follower_id, class_name: 'Follow'
  has_many :following, through: :following_relationships, source: :following

  after_create :subscribe_user_to_mailing_list

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	validates :name, presence: true

  private

  def subscribe_user_to_mailing_list
    SubscribeUserToMailingListJob.perform_later(self)
  end

  def follow(user_id)
      following_relationships.create(following_id: user_id)
    end

    def unfollow(user_id)
      following_relationships.find_by(following_id: user_id).destroy
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 # Prevent CSRF attacks by raising an exception.
 # For APIs, you may want to use :null_session instead.
 protect_from_forgery with: :exception
 before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :username, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :username, :email, :password, :current_password, :bio) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = current_user.comments.build(comment_params)
  end

  private
  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def about
  end

  def how_it_works
  end

  def contact
  end

  def faq
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy, :like]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @pins = Pin.pin_search(params[:search]).page(params[:page]).per(6)
  end

  def like
    @like = @pin.likes.build(user_id: current_user.id)
    if @like.save
      redirect_to pins_path, notice: 'You liked this file.'
    else
      redirect_to pins_path, notice: 'You have already liked this file.'
    end
  end

  def show
    @pin = Pin.includes(:comments).find_by_param(params[:id])
    @comment = Comment.new
    @pin.count_views
  end

  def new
    @pin = current_user.pins.build
  end

  def edit
  end

  def create
    @pin = current_user.pins.build(pin_params)
    @pin.view = 0
    if @pin.save
      redirect_to @pin, notice: 'Post was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @pin.destroy
    redirect_to pins_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find_by_param(params[:id])
    end

    def correct_user
      @pin = current_user.pins.find_by_param(params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this post" if @pin.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image, :link)
    end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def follow_user
    @user = User.find_by! username: params[:username]
    if current_user.follow @user.id
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    end
  end

  def unfollow_user
    @user = User.find_by! username: params[:username]
    if current_user.unfollow @user.id
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
     @user = User.find(params[:id])
     @user_pins = @user.pins
  end

  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follow'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user_is_following(current_user_id, followed_user_id)
    relationship = Follow.find_by(follower_id: current_user_id, following_id: followed_user_id)
    return true if relationship
  end
end

app/views/comments/_comment.html.erb
<div class="comment-card">
  <div class="card">
    <div class="card-block">
      <div class="row">
        <div class="col-md-12">
          <div class="comment-user"><%= comment.user.username %></div>
          <%= comment.content %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/comments/_comment_form.html.erb
<div class="col-md-offset-2 col-md-8">
  <%= form_for @comment, url: '#' do |f| %>
    <div class="form-group">
      <%= f.label :content, 'Comments' %>
      <%= f.text_area :content, class: 'form-control' %>
    </div>
    <%= f.submit 'Post Comment', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer>
	<div class="container">
	    	<ul>
	      		<li><%= link_to "Our Story", about_path %></li>
	      		<li><%= link_to "How it Works", how_it_works_path %></li>
	      		<li><a href="https://drive.google.com/drive/folders/0B_peADpdLkoLT3RmUFl2cDB4bmM?usp=sharing">Press Kit</a></li>
	      		<li><%= link_to "FAQ", faq_path %></li>
	      		<li><%= link_to "Contact", contact_path %></li>
	      		<li><a href="https://medium.com/@treasurably">Blog</a></li>
	    	</ul>
	</div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <div class="container navigation-bar ">

    <!-- Logo -->

    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Treasurably", root_path, class: "navbar-brand" %>
    </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
          <li><%= link_to new_pin_path do %>
          <span class="glyphicon glyphicon-plus"></span> Share Cloud Storage
              <% end %>
            </li>
          <li><%= link_to "Account Settings", edit_user_registration_path %></li>
            <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Beta Login", new_user_session_path, class: 'btn btn-default beta-login' %></li>
          <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.containter -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Treasurably</title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Raleway' %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>
	<%= render 'layouts/header' %>
	<div class="container">
    <%= form_tag pins_path, method: :get, html: {class: "gl-search" } do |f| %>
      <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search files across Drive, Docs, Dropbox and more ..." %>
    <% end %>
		<% flash.each do |name, msg| %>
     	<%= content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>
		<%= yield %>
   	</div>
    <div class="page-footer">
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>

app/views/pages/_home.html.erb
<div class="jumbotron left">
	<h1>Do More With Cloud Storage</h1>
	&nbsp;
	<p>
	<h3>Cloud storage has changed the way we use, work and access files on the web. We love it, and our goal is to make it even better!</h3> 

	<h3>Treasurably is the one stop location to manage your cloud files and folders. It allows you to share, search, like and interact across Dropbox, Drive, and Docs ... all at the same time.<h/3> 

	<h3>Uncover incredible files from makers, marketers, designers, educators, and much more. It's like a cloud storage search engine, and here's the best thing - it's free. &#128079;</h3> 
	</p>
	&nbsp;
		<p>
			<%= link_to "How it Works", how_it_works_path, class: "btn btn-lg btn-primary" %>
		</p>
</div>
<div>
</div>
 

app/views/pages/about.html.erb
<h1>More Information About Treasurably</h1>
&nbsp;
<p>
<h3>Treasurably <u>does not scrape public files,</u> instead allows people to share cloud resources - enabling anyone to instantly search across all cloud storage services, and platforms.</h3> 
</p>

<p>
<h3>You can like posts, follow brands or people you love, and get immediate access to incredible resources.</h3>
</p>

<p>
<h3>There are over 1 billion+ people who use Dropbox, Google Drive, Google Sheets, Google Docs, Microsoft OneNote, Box, and Trello.</h3>
</p> 

<p>
<h3>We imagine what would the world be like if brands like Apple shared their internal design resources publicly, colleges shared their lecture notes, industrial designers shared their 3D model designs, or even Rugby coaches shared their gameplays, and strategies. Would the world be better off? Abosolutely!
</p>

<p>
<h3>Our vision is to make the world more knowledgeable, for our generation, and generations to come.</h3>
</p>
&nbsp;

app/views/pages/contact.html.erb
<h1>Contact Us</h1>
&nbsp;
<h4>Hi there! Treasurably is here to provide you with more information, or answer any questions you may have.</h4>
&nbsp;
<h4>Our contact details:</h4>
&nbsp;
<ul>
	<li><h4>Email: team@treasurably.com</h4></li>
	<li><h4>Luke Fitzpatrick: luke@treasurably.com</h4></li>
	<li><h4>Liam Gibson: liam@treasurably.com</h4></li>
  	<li><h4>Phone: +614 5011 6822</h4></li>
  	<li><h4>Address: Sydney, Australia</h4></li>
  	<li><h4>Skype: lukejamesfitzpatrick</h4></li>
  	&nbsp;
</ul>
&nbsp;

<h4>Connect with us socially (to be updated soon):</h4>
&nbsp;
<ul>
	<li><h4>Facebook: </h4></li>
	<li><h4>Twitter: </h4></li>
	<li><h4>LinkedIn: </h4></li>
  	<li><h4>YouTube: </h4></li>
  	<li><h4>AngelList: </h4></li>
  	<li><h4>CrunchBase: </h4></li>
  	<li><h4>Medium: </h4></li>
  	&nbsp;
</ul>
&nbsp;

app/views/pages/faq.html.erb
<h1>Frequently Asked Questions</h1>
&nbsp;

<h3>How does Treasurably work?</h3>
<p>With Treasurably, you can share you cloud storage URL's, search files that have been shared on our platform, like posts, see how many people have viewed your posts, follow people and much more ...</p>

<h3>Does Treasurably cost money to use?</h3>
<p>Treasurably is totally free to use and we hope you like it as much as we do.</p>

<h3>How are you able to search public cloud storage files?</h3>
<p>We don't scrape cloud storage public files, instead, we allow anyone to share their files on to our platform. This allows the world to find them.</p>

<h3>Who is Treasurably for?</h3>
<p>Treasurably is pretty for everyone. That means, marketers, designers, programmers, educators, doctors, sporting coaches, or even NASA scientists.</p>

<h3>Why should I share my cloud storage files?</h3>
<p>People share their cloud storage files for a number of reasons ... They may want to make the world more knowledgeable, or using Treasurably as a mechanism for branding.</p>

<h3>What happens if I see someone violate copyright infringement?</h3>
<p>Send us an email to team@treasurably.com. Right now, we haven't set up a system for "flagging" posts, but in the near future, we hope to include this feature.</p>

<h3>How can I get immediate early access to use Treasurably?</h3>
<p>At present, we're only letting a select few try out Treasurably. However, if you have useful cloud storage files you'd like to share with the world, shoot us an email at luke@treasurably.com and we'll give you early access.</p>

<h3>Do you provide multiple usernames?</h3>
<p>Unfortunately, we don't. That means that only one person can have one username - so make sure you claim yours now before someone else snaps it up.</p>

<h3>How can I get in touch with you?</h3>
<p>Feel free to email us at team@treasurably.com.</p>

<h3>When will Treasurably be available for public consumption?</h3>
<p>Our web application has been built, it's live now. However, officially we haven't launched as we're in the final stages of bug testing and adding in design improvements. We expect to officially launch mid-November.</p>

<h3>I have some general product suggestions I'd love to give you.</h3>
<p>That's great! Come join our Meta community, allowing you to give feedback, new feature suggestions, chat with other members, and be directly involved in shaping the future of Treasurably.</p>
&nbsp;

app/views/pages/home.html.erb
<div class="jumbotron center">
	<h1>Showcase Your Code </h1>
	 <% if user_signed_in? %>
          # do something
     <% else %>
	<p>
		<%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
		<%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
	</p>
<% end %>  

</div>

app/views/pages/how_it_works.html.erb
<h1>How does Treasurably Work?</h1>
&nbsp;
<h3>Treasurably is a place to search or share cloud storage files. We'll walk you through a few things you should know to get you started.</h3>
&nbsp;

<p>
<h2><u>Sharing Cloud Files and Folders</u></h2>
&nbsp;

<h3>Step 1: Click "Share Cloud Storage."</h3>
<h3>Step 2: Add your cloud storage link and image.</h3>
<h3>Step 3: Then, hit "Submit."</h3>

&nbsp;
<h2><u>How Do I Get Access to Somebody's Cloud Files?</u></h2>
&nbsp;

<h3>Step 1: Click on the post link.</h3>
<h3>Step 2: Click the green "get" button.</h3>
<h3>Step 3: Then, it'll be automatically added to your Google Drive, Docs etc. No download required. Pretty sweet, right?</h3>

&nbsp;
<h2><u>Searching Cloud Storage Files and Folders</u></h2>
&nbsp;

<h3>-> You can search <u>every</u> cloud storage application (Drive, Docs, Dropbox, Trello, Microsoft OneNote etc).</h3>
<h3>-> Tresurably <u>only</u> searches public cloud storage files that have been shared on to our platform.</h3>
<h3>-> Searching only <u>matches</u> the description of the file. It does not <u>search</u> inside your cloud files.</h3>
&nbsp;

<h2><u>Treasurably Features</u></h2>
&nbsp;

<h3>-> Search cloud storage files.</h3>
<h3>-> User profiles.</h3>
<h3>-> Follower and Followers.</h3>
<h3>-> Unique usernames (only 1).</h3>
<h3>-> Post comments (when signed in).</h3>
<h3>-> Treasurably is currently invite-only.</h3>
<h3>-> And, free.</h3>
&nbsp;
</p>
&nbsp;

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :link %>
    <%= f.text_field :link, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit 'Submit', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing Post</h1>

<div class="form-format">
  <%= render 'form' %>
  <%= link_to 'Show', @pin %>
  <%= link_to 'Back', pins_path %>
</div>

app/views/pins/index.html.erb
<%= render 'pages/home' unless user_signed_in? %>

<div id="pins" class="transitions-enabled">
  <% @pins.each do |pin| %>
    <div class="box panel panel-default">
      <%= link_to image_tag(pin.image.url(:medium)), pin %>
      <div class="panel-body">
        <p><%= pin.description %></p>
        <p><strong><%= link_to pin.user.username, user_page_path(pin.user.id) %></strong></p>
        <span><%= pin.likes.count %></span> <span class="glyphicon glyphicon-heart"></span>
        <span><%= pin.view %></span> <i class="glyphicon glyphicon-eye-open"></i>

        <% if pin.user == current_user %>
          <div class="actions">
            <%= link_to edit_pin_path(pin) do %>
              <span class="glyphicon glyphicon-edit"></span>
              Edit
            <% end %>
            <%= link_to pin, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <span class="glyphicon glyphicon-trash"></span>
              Delete
            <% end %>
          </div>
        <% end %>
        <% if pin.user != current_user %>
          <%= link_to 'Like', like_pin_path(pin), method: :post, class: 'pull-right, btn btn-sm btn-like btn-success' %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<div class="center">
  <%= paginate @pins %>
</div>

app/views/pins/new.html.erb
<h1>Share Cloud Storage</h1>

<div class="form-format">
  <%= render 'form' %>
  <%= link_to 'Back', pins_path %>
</div>

app/views/pins/show.html.erb
<%= link_to 'Back', pins_path, class: "btn btn-default" %>

<div class="row single-pin">
  <div class="col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading center">
        <%= image_tag @pin.image.url(:medium) %>
      </div>
      <div class="panel-body">
        <p><strong><%= link_to @pin.user.username, user_page_path(@pin.user.id) %></strong></p>
        <p><%= @pin.description %></p>
        <span><%= @pin.likes.count %></span> <span class="glyphicon glyphicon-heart"></span>
        <span><%= @pin.view %></span> <i class="glyphicon glyphicon-eye-open"></i>
        <p><span class="gl-edit"><% if @pin.user == current_user %>
          <%= link_to edit_pin_path(@pin) do %>
            <span class="glyphicon glyphicon-edit"></span>
            Edit
          <% end %>
        <% end %></span>
        <%= link_to "Get", @pin.link, class: "btn btn-sm btn-success btn-get" %>
        <% if @pin.user != current_user %>
          <%= link_to 'Like', like_pin_path(@pin), method: :post, class: 'pull-right, btn btn-sm btn-like btn-success' %>
        <% end %></p>
      </div>
    </div>
  </div>
  <!-- Start of comments -->
  <% if current_user %>
    <%= render 'comments/comment_form' %>
  <% end %>
  <div class="col-md-offset-2 col-md-8">
    <div id="comments" data-pin-id="<%= @pin.id %>">
      <%= render @pin.comments %>
    </div>
  </div>
  <!-- End of comments -->
</div>

app/views/relationships/follow_user.html.erb
<h1>Relationships#follow_user</h1>
<p>Find me in app/views/relationships/follow_user.html.erb</p>

app/views/relationships/follow_user.js.erb
$('#follow-button').attr('class', 'btn btn-sm unfollow-button')
                   .text('Unfollow')
                   .attr('href', "/<%= @user.username %>/unfollow_user")
                   .attr('id', 'unfollow-button');

app/views/relationships/unfollow_user.html.erb
<h1>Relationships#unfollow_user</h1>
<p>Find me in app/views/relationships/unfollow_user.html.erb</p>

app/views/relationships/unfollow_user.js.erb
$('#unfollow-button').text('Follow')
                     .attr('class', 'btn btn-sm follow-button')
                     .attr('href', "/<%= @user.username %>/follow_user")
                     .attr('id', 'follow-button');

app/views/users/show.html.erb
<div class="user-profile">
  <span class="profile-username"><%= link_to @user.username, user_page_path(@user) %></span>
  <% if @user == current_user %>
    <% if current_user_is_following(current_user.id, @user.id) %>
      <%= link_to 'Unfollow', unfollow_user_path(@user.username), remote: true, class: 'btn btn-sm unfollow-button', id: 'unfollow-button', method: :post %>
    <% else %>
      <%= link_to 'Follow', follow_user_path(@user.username), remote: true, class: 'btn btn-sm follow-button', id: 'follow-button', method: :post %>
    <% end %>
    <% else %>
    <%= link_to "Edit", edit_user_registration_path, class: 'btn btn-info btn-sm' %>
  <% end %>

  <div>
    <div class="profile-soc">
      <span class="profile-follow"><%= @user.pins.count %> <%= 'file'.pluralize(@user.pins.count)%></span>
      <span class="profile-follow"><%= link_to "#{@user.followers.count} followers".pluralize(@user.followers.count), followers_user_path %></span>
      <span class="profile-follow"><%= link_to "#{@user.following.count} following", following_user_path %></span>
    </div>
    <p><%= @user.bio %></p>
  </div>
</div>

<div id="pins" class="transitions-enabled">
  <% @user.pins.each do |pin| %>
    <div class="box panel panel-default">
      <%= link_to image_tag(pin.image.url(:medium)), pin %>
      <div class="panel-body">
        <p><%= pin.description %></p>
        <p><strong><%= link_to pin.user.username if pin.user %></strong></p>
        <p><%= pluralize(pin.likes.count, "like") %></p>
          <span class="glyphicon glyphicon-heart"></span>

        <% if pin.user == current_user %>
          <div class="actions">
            <%= link_to edit_pin_path(pin) do %>
              <span class="glyphicon glyphicon-edit"></span>
              Edit
            <% end %>
            <%= link_to pin, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <span class="glyphicon glyphicon-trash"></span>
              Delete
            <% end %>
          </div>
        <% end %>
        <% if pin.user != current_user %>
          <%= link_to 'Like', like_pin_path(pin), method: :post, class: 'pull-right, btn btn-sm btn-like btn-success' %>
        <% end %>

      </div>
    </div>
  <% end %>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1><%= @user.username %></h1>
      <span><%= link_to "view my profile", @user %></span>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% @users.each do |user| %>
      <div class="card-block">
        <div class="row">
          <div class="col-md-12">
            <%= user.username %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>